# Generated by Django 3.0.6 on 2020-06-02 09:00

from django.db import migrations
from website.models import IngredientType

names = ['légume', 'viande', 'poisson', 'fruit', 'épice', 'féculent']

def create_types(apps, schema_editor):
    for name in names:
        IngredientType.objects.create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200602_0857'),
    ]

    operations = [
        migrations.RunPython(create_types),
    ]
