# Generated by Django 3.0.6 on 2020-06-02 09:42

from django.db import migrations

from website.models import IngredientType, Ingredient

# def create_ingredients(apps, schema_editor):
#     vegetable = Type.object.get(name='légume')
#     meat = Type.object.get(name='viande')
#     fish = Type.object.get(name='poisson')
#     fruit = Type.object.get(name='fruit')
#     spice = Type.object.get(name='épice')
#
#     vegetables = [
#         'brocolis', 'chou-fleur', 'carotte', 'haricot', 'courgette', 'courge',
#         'potiron', 'salade', 'endive', 'fenouil', 'topinambour'
#     ]
#
#     meats = ['boeuf', 'canard', 'lapin', 'agneau', 'poulet']
#
#     fishes = ['anchois', 'saumon', 'truite', 'maquerau', 'lieu']
#
#     fruits = [
#         'banane', 'melon', 'pomme', 'poire', 'abricot', 'mangue', 'pêche',
#         'cerise', 'mirabelle', 'raisin'
#     ]
#
#     spices = ['curry', 'cumin', 'sel', 'poivre', 'thym', 'basilic', 'menthe']
#
#     list_ = [
#         {'type': vegetable, 'list': vegetables},
#         {'type': meat, 'list': meats},
#         {'type': fruit, 'list': fruits},
#         {'type': sice, 'list': sices},
#         {'type': fish, 'list': fishes},
#     ]
#
#     for v in vegetables:
#         Ingredient.create(name=v, type=vegetable)

    # for dict_ in list_:
    #     for item in dict_['list']:
    #         Ingredient.create(name=item, type=dict_['type'])


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200602_0900'),
    ]

    operations = [
    ]
