# Generated by Django 3.0.6 on 2020-06-02 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_create_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='canned_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.CannedFood'),
        ),
    ]
