# Generated by Django 3.0.6 on 2020-06-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_create_ingredient_v2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='canned_food',
        ),
        migrations.AddField(
            model_name='cannedfood',
            name='ingredients',
            field=models.ManyToManyField(to='website.Ingredient'),
        ),
    ]
