# Generated by Django 3.0.6 on 2020-06-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='IngredientType',
        ),
    ]
