# Generated by Django 3.0.6 on 2020-06-10 09:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200610_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='CannedFoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='cannedfood',
            name='limited_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='cannedfood',
            name='note',
            field=models.TextField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(default=0)),
                ('delivery_number', models.CharField(max_length=100)),
                ('canned_food', models.ManyToManyField(to='website.CannedFood')),
            ],
        ),
        migrations.AddField(
            model_name='cannedfood',
            name='stock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='website.Stock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cannedfood',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='website.CannedFoodType'),
            preserve_default=False,
        ),
    ]
