# Generated by Django 3.0.6 on 2020-06-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200610_0914'),
        ('website', '0008_auto_20200603_0742'),
    ]

    operations = [
    ]
