# Generated by Django 3.0.6 on 2020-06-10 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_merge_20200610_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cannedfood',
            name='stock',
        ),
        migrations.AddField(
            model_name='stock',
            name='cannedfood',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='website.CannedFood'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cannedfood',
            name='note',
            field=models.TextField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
