# Generated by Django 3.0.6 on 2020-06-11 14:28

from django.db import migrations
from django.contrib.auth.models import User


def create_superuser(apps, schema_editor):
    User.objects.create_superuser('admin', '', 'admin')


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20200610_1405'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
