# Generated by Django 3.0.6 on 2020-06-11 15:13
import random

from django.db import migrations
from website.models import Ingredient, CannedFood, CannedFoodType


def rand_name(a_list):
    return "".join(l.name[:3] for l in a_list[:3])


def create_canned_food(apps, schema_editor):
    ingredients_id = [i.id for i in Ingredient.objects.all()]

    types = CannedFoodType.objects.all()

    for i in range(4):
        rand_n = random.randrange(1, 8)
        rand_ids = random.sample(ingredients_id, rand_n)
        rand_ingredients = Ingredient.objects.filter(id__in=rand_ids)

        note = "je suis une note robot"
        random_price = random.randrange(1, 30)
        random_type = types[random.randrange(len(types))]
        random_name = rand_name(rand_ingredients)

        c = CannedFood.objects.create(
            name=random_name, note=note,
            type=random_type, price=random_price
        )
        c.ingredients.add(*rand_ingredients)


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_create_cannedfood_type'),
    ]

    operations = [
        migrations.RunPython(create_canned_food)
    ]
