# Generated by Django 3.0.6 on 2020-06-11 15:13
import random

from django.db import migrations
from website.models import Stock, CannedFood


def create_stock(apps, schema_editor):
    canned_food = CannedFood.objects.all()
    for c in canned_food:
        for i in range(3):
            random_weight = random.randrange(100, 1000)
            random_quantity = random.randrange(15)
            Stock.objects.create(
                weight=random_weight, quantity=random_quantity,
                cannedfood=c
            )


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_create_cannedfood'),
    ]

    operations = [
        migrations.RunPython(create_stock)
    ]
