# Generated by Django 3.0.6 on 2020-06-16 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='orderitems',
            new_name='cartitems',
        ),
    ]
